// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/protobuf/BookMsg.proto

package com.bhz.netty.protobuf;

public final class BookProto {
  private BookProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface BookMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BookMsg)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .Book books = 1;</code>
     */
    boolean hasBooks();
    /**
     * <code>optional .Book books = 1;</code>
     */
    com.bhz.netty.protobuf.BookProto.Book getBooks();

    /**
     * <code>optional .Author author = 2;</code>
     */
    boolean hasAuthor();
    /**
     * <code>optional .Author author = 2;</code>
     */
    com.bhz.netty.protobuf.BookProto.Author getAuthor();
  }
  /**
   * Protobuf type {@code BookMsg}
   */
  public static final class BookMsg extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:BookMsg)
      BookMsgOrBuilder {
    // Use BookMsg.newBuilder() to construct.
    private BookMsg(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BookMsg(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final BookMsg defaultInstance;
    public static BookMsg getDefaultInstance() {
      return defaultInstance;
    }

    public BookMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private BookMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.bhz.netty.protobuf.BookProto.Book.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = books_.toBuilder();
              }
              books_ = input.readMessage(com.bhz.netty.protobuf.BookProto.Book.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(books_);
                books_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.bhz.netty.protobuf.BookProto.Author.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = author_.toBuilder();
              }
              author_ = input.readMessage(com.bhz.netty.protobuf.BookProto.Author.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(author_);
                author_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<BookMsg> PARSER =
        new com.google.protobuf.AbstractParser<BookMsg>() {
      public BookMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BookMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BookMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BOOKS_FIELD_NUMBER = 1;
    private com.bhz.netty.protobuf.BookProto.Book books_;
    /**
     * <code>optional .Book books = 1;</code>
     */
    public boolean hasBooks() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Book books = 1;</code>
     */
    public com.bhz.netty.protobuf.BookProto.Book getBooks() {
      return books_;
    }

    public static final int AUTHOR_FIELD_NUMBER = 2;
    private com.bhz.netty.protobuf.BookProto.Author author_;
    /**
     * <code>optional .Author author = 2;</code>
     */
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Author author = 2;</code>
     */
    public com.bhz.netty.protobuf.BookProto.Author getAuthor() {
      return author_;
    }

    private void initFields() {
      books_ = com.bhz.netty.protobuf.BookProto.Book.getDefaultInstance();
      author_ = com.bhz.netty.protobuf.BookProto.Author.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, books_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, author_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, books_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, author_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bhz.netty.protobuf.BookProto.BookMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bhz.netty.protobuf.BookProto.BookMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bhz.netty.protobuf.BookProto.BookMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bhz.netty.protobuf.BookProto.BookMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bhz.netty.protobuf.BookProto.BookMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bhz.netty.protobuf.BookProto.BookMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bhz.netty.protobuf.BookProto.BookMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bhz.netty.protobuf.BookProto.BookMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bhz.netty.protobuf.BookProto.BookMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bhz.netty.protobuf.BookProto.BookMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bhz.netty.protobuf.BookProto.BookMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code BookMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.bhz.netty.protobuf.BookProto.BookMsg, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:BookMsg)
        com.bhz.netty.protobuf.BookProto.BookMsgOrBuilder {
      // Construct using com.bhz.netty.protobuf.BookProto.BookMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        books_ = com.bhz.netty.protobuf.BookProto.Book.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        author_ = com.bhz.netty.protobuf.BookProto.Author.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.bhz.netty.protobuf.BookProto.BookMsg getDefaultInstanceForType() {
        return com.bhz.netty.protobuf.BookProto.BookMsg.getDefaultInstance();
      }

      public com.bhz.netty.protobuf.BookProto.BookMsg build() {
        com.bhz.netty.protobuf.BookProto.BookMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bhz.netty.protobuf.BookProto.BookMsg buildPartial() {
        com.bhz.netty.protobuf.BookProto.BookMsg result = new com.bhz.netty.protobuf.BookProto.BookMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.books_ = books_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.author_ = author_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.bhz.netty.protobuf.BookProto.BookMsg other) {
        if (other == com.bhz.netty.protobuf.BookProto.BookMsg.getDefaultInstance()) return this;
        if (other.hasBooks()) {
          mergeBooks(other.getBooks());
        }
        if (other.hasAuthor()) {
          mergeAuthor(other.getAuthor());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bhz.netty.protobuf.BookProto.BookMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bhz.netty.protobuf.BookProto.BookMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.bhz.netty.protobuf.BookProto.Book books_ = com.bhz.netty.protobuf.BookProto.Book.getDefaultInstance();
      /**
       * <code>optional .Book books = 1;</code>
       */
      public boolean hasBooks() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Book books = 1;</code>
       */
      public com.bhz.netty.protobuf.BookProto.Book getBooks() {
        return books_;
      }
      /**
       * <code>optional .Book books = 1;</code>
       */
      public Builder setBooks(com.bhz.netty.protobuf.BookProto.Book value) {
        if (value == null) {
          throw new NullPointerException();
        }
        books_ = value;

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Book books = 1;</code>
       */
      public Builder setBooks(
          com.bhz.netty.protobuf.BookProto.Book.Builder builderForValue) {
        books_ = builderForValue.build();

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Book books = 1;</code>
       */
      public Builder mergeBooks(com.bhz.netty.protobuf.BookProto.Book value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            books_ != com.bhz.netty.protobuf.BookProto.Book.getDefaultInstance()) {
          books_ =
            com.bhz.netty.protobuf.BookProto.Book.newBuilder(books_).mergeFrom(value).buildPartial();
        } else {
          books_ = value;
        }

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Book books = 1;</code>
       */
      public Builder clearBooks() {
        books_ = com.bhz.netty.protobuf.BookProto.Book.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      private com.bhz.netty.protobuf.BookProto.Author author_ = com.bhz.netty.protobuf.BookProto.Author.getDefaultInstance();
      /**
       * <code>optional .Author author = 2;</code>
       */
      public boolean hasAuthor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Author author = 2;</code>
       */
      public com.bhz.netty.protobuf.BookProto.Author getAuthor() {
        return author_;
      }
      /**
       * <code>optional .Author author = 2;</code>
       */
      public Builder setAuthor(com.bhz.netty.protobuf.BookProto.Author value) {
        if (value == null) {
          throw new NullPointerException();
        }
        author_ = value;

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Author author = 2;</code>
       */
      public Builder setAuthor(
          com.bhz.netty.protobuf.BookProto.Author.Builder builderForValue) {
        author_ = builderForValue.build();

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Author author = 2;</code>
       */
      public Builder mergeAuthor(com.bhz.netty.protobuf.BookProto.Author value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            author_ != com.bhz.netty.protobuf.BookProto.Author.getDefaultInstance()) {
          author_ =
            com.bhz.netty.protobuf.BookProto.Author.newBuilder(author_).mergeFrom(value).buildPartial();
        } else {
          author_ = value;
        }

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Author author = 2;</code>
       */
      public Builder clearAuthor() {
        author_ = com.bhz.netty.protobuf.BookProto.Author.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BookMsg)
    }

    static {
      defaultInstance = new BookMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BookMsg)
  }

  public interface BookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Book)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string bookId = 1;</code>
     */
    boolean hasBookId();
    /**
     * <code>optional string bookId = 1;</code>
     */
    java.lang.String getBookId();
    /**
     * <code>optional string bookId = 1;</code>
     */
    com.google.protobuf.ByteString
        getBookIdBytes();

    /**
     * <code>optional string bookName = 2;</code>
     */
    boolean hasBookName();
    /**
     * <code>optional string bookName = 2;</code>
     */
    java.lang.String getBookName();
    /**
     * <code>optional string bookName = 2;</code>
     */
    com.google.protobuf.ByteString
        getBookNameBytes();

    /**
     * <code>optional float price = 3;</code>
     */
    boolean hasPrice();
    /**
     * <code>optional float price = 3;</code>
     */
    float getPrice();

    /**
     * <code>optional .Author author = 4;</code>
     */
    boolean hasAuthor();
    /**
     * <code>optional .Author author = 4;</code>
     */
    com.bhz.netty.protobuf.BookProto.Author getAuthor();
  }
  /**
   * Protobuf type {@code Book}
   */
  public static final class Book extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:Book)
      BookOrBuilder {
    // Use Book.newBuilder() to construct.
    private Book(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Book(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final Book defaultInstance;
    public static Book getDefaultInstance() {
      return defaultInstance;
    }

    public Book getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private Book(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              bookId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              bookName_ = bs;
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              price_ = input.readFloat();
              break;
            }
            case 34: {
              com.bhz.netty.protobuf.BookProto.Author.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = author_.toBuilder();
              }
              author_ = input.readMessage(com.bhz.netty.protobuf.BookProto.Author.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(author_);
                author_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Book> PARSER =
        new com.google.protobuf.AbstractParser<Book>() {
      public Book parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Book(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Book> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BOOKID_FIELD_NUMBER = 1;
    private java.lang.Object bookId_;
    /**
     * <code>optional string bookId = 1;</code>
     */
    public boolean hasBookId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string bookId = 1;</code>
     */
    public java.lang.String getBookId() {
      java.lang.Object ref = bookId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bookId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string bookId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBookIdBytes() {
      java.lang.Object ref = bookId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOOKNAME_FIELD_NUMBER = 2;
    private java.lang.Object bookName_;
    /**
     * <code>optional string bookName = 2;</code>
     */
    public boolean hasBookName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string bookName = 2;</code>
     */
    public java.lang.String getBookName() {
      java.lang.Object ref = bookName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bookName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string bookName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBookNameBytes() {
      java.lang.Object ref = bookName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 3;
    private float price_;
    /**
     * <code>optional float price = 3;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional float price = 3;</code>
     */
    public float getPrice() {
      return price_;
    }

    public static final int AUTHOR_FIELD_NUMBER = 4;
    private com.bhz.netty.protobuf.BookProto.Author author_;
    /**
     * <code>optional .Author author = 4;</code>
     */
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Author author = 4;</code>
     */
    public com.bhz.netty.protobuf.BookProto.Author getAuthor() {
      return author_;
    }

    private void initFields() {
      bookId_ = "";
      bookName_ = "";
      price_ = 0F;
      author_ = com.bhz.netty.protobuf.BookProto.Author.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBookIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getBookNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, price_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, author_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBookIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBookNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, price_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, author_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bhz.netty.protobuf.BookProto.Book parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bhz.netty.protobuf.BookProto.Book parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bhz.netty.protobuf.BookProto.Book parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bhz.netty.protobuf.BookProto.Book parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bhz.netty.protobuf.BookProto.Book parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bhz.netty.protobuf.BookProto.Book parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bhz.netty.protobuf.BookProto.Book parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bhz.netty.protobuf.BookProto.Book parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bhz.netty.protobuf.BookProto.Book parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bhz.netty.protobuf.BookProto.Book parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bhz.netty.protobuf.BookProto.Book prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code Book}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.bhz.netty.protobuf.BookProto.Book, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:Book)
        com.bhz.netty.protobuf.BookProto.BookOrBuilder {
      // Construct using com.bhz.netty.protobuf.BookProto.Book.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bookId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        bookName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        author_ = com.bhz.netty.protobuf.BookProto.Author.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.bhz.netty.protobuf.BookProto.Book getDefaultInstanceForType() {
        return com.bhz.netty.protobuf.BookProto.Book.getDefaultInstance();
      }

      public com.bhz.netty.protobuf.BookProto.Book build() {
        com.bhz.netty.protobuf.BookProto.Book result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bhz.netty.protobuf.BookProto.Book buildPartial() {
        com.bhz.netty.protobuf.BookProto.Book result = new com.bhz.netty.protobuf.BookProto.Book(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bookId_ = bookId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bookName_ = bookName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.author_ = author_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.bhz.netty.protobuf.BookProto.Book other) {
        if (other == com.bhz.netty.protobuf.BookProto.Book.getDefaultInstance()) return this;
        if (other.hasBookId()) {
          bitField0_ |= 0x00000001;
          bookId_ = other.bookId_;
          
        }
        if (other.hasBookName()) {
          bitField0_ |= 0x00000002;
          bookName_ = other.bookName_;
          
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasAuthor()) {
          mergeAuthor(other.getAuthor());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bhz.netty.protobuf.BookProto.Book parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bhz.netty.protobuf.BookProto.Book) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object bookId_ = "";
      /**
       * <code>optional string bookId = 1;</code>
       */
      public boolean hasBookId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string bookId = 1;</code>
       */
      public java.lang.String getBookId() {
        java.lang.Object ref = bookId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bookId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bookId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBookIdBytes() {
        java.lang.Object ref = bookId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bookId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bookId = 1;</code>
       */
      public Builder setBookId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bookId_ = value;
        
        return this;
      }
      /**
       * <code>optional string bookId = 1;</code>
       */
      public Builder clearBookId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bookId_ = getDefaultInstance().getBookId();
        
        return this;
      }
      /**
       * <code>optional string bookId = 1;</code>
       */
      public Builder setBookIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bookId_ = value;
        
        return this;
      }

      private java.lang.Object bookName_ = "";
      /**
       * <code>optional string bookName = 2;</code>
       */
      public boolean hasBookName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string bookName = 2;</code>
       */
      public java.lang.String getBookName() {
        java.lang.Object ref = bookName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bookName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bookName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBookNameBytes() {
        java.lang.Object ref = bookName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bookName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bookName = 2;</code>
       */
      public Builder setBookName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bookName_ = value;
        
        return this;
      }
      /**
       * <code>optional string bookName = 2;</code>
       */
      public Builder clearBookName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bookName_ = getDefaultInstance().getBookName();
        
        return this;
      }
      /**
       * <code>optional string bookName = 2;</code>
       */
      public Builder setBookNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bookName_ = value;
        
        return this;
      }

      private float price_ ;
      /**
       * <code>optional float price = 3;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional float price = 3;</code>
       */
      public float getPrice() {
        return price_;
      }
      /**
       * <code>optional float price = 3;</code>
       */
      public Builder setPrice(float value) {
        bitField0_ |= 0x00000004;
        price_ = value;
        
        return this;
      }
      /**
       * <code>optional float price = 3;</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        price_ = 0F;
        
        return this;
      }

      private com.bhz.netty.protobuf.BookProto.Author author_ = com.bhz.netty.protobuf.BookProto.Author.getDefaultInstance();
      /**
       * <code>optional .Author author = 4;</code>
       */
      public boolean hasAuthor() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Author author = 4;</code>
       */
      public com.bhz.netty.protobuf.BookProto.Author getAuthor() {
        return author_;
      }
      /**
       * <code>optional .Author author = 4;</code>
       */
      public Builder setAuthor(com.bhz.netty.protobuf.BookProto.Author value) {
        if (value == null) {
          throw new NullPointerException();
        }
        author_ = value;

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Author author = 4;</code>
       */
      public Builder setAuthor(
          com.bhz.netty.protobuf.BookProto.Author.Builder builderForValue) {
        author_ = builderForValue.build();

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Author author = 4;</code>
       */
      public Builder mergeAuthor(com.bhz.netty.protobuf.BookProto.Author value) {
        if (((bitField0_ & 0x00000008) == 0x00000008) &&
            author_ != com.bhz.netty.protobuf.BookProto.Author.getDefaultInstance()) {
          author_ =
            com.bhz.netty.protobuf.BookProto.Author.newBuilder(author_).mergeFrom(value).buildPartial();
        } else {
          author_ = value;
        }

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Author author = 4;</code>
       */
      public Builder clearAuthor() {
        author_ = com.bhz.netty.protobuf.BookProto.Author.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Book)
    }

    static {
      defaultInstance = new Book(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Book)
  }

  public interface AuthorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Author)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string authorName = 1;</code>
     */
    boolean hasAuthorName();
    /**
     * <code>optional string authorName = 1;</code>
     */
    java.lang.String getAuthorName();
    /**
     * <code>optional string authorName = 1;</code>
     */
    com.google.protobuf.ByteString
        getAuthorNameBytes();

    /**
     * <code>optional string address = 2;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 2;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 2;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>repeated .Book books = 3;</code>
     */
    java.util.List<com.bhz.netty.protobuf.BookProto.Book> 
        getBooksList();
    /**
     * <code>repeated .Book books = 3;</code>
     */
    com.bhz.netty.protobuf.BookProto.Book getBooks(int index);
    /**
     * <code>repeated .Book books = 3;</code>
     */
    int getBooksCount();
  }
  /**
   * Protobuf type {@code Author}
   */
  public static final class Author extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:Author)
      AuthorOrBuilder {
    // Use Author.newBuilder() to construct.
    private Author(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Author(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final Author defaultInstance;
    public static Author getDefaultInstance() {
      return defaultInstance;
    }

    public Author getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private Author(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              authorName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              address_ = bs;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                books_ = new java.util.ArrayList<com.bhz.netty.protobuf.BookProto.Book>();
                mutable_bitField0_ |= 0x00000004;
              }
              books_.add(input.readMessage(com.bhz.netty.protobuf.BookProto.Book.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          books_ = java.util.Collections.unmodifiableList(books_);
        }
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Author> PARSER =
        new com.google.protobuf.AbstractParser<Author>() {
      public Author parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Author(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Author> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int AUTHORNAME_FIELD_NUMBER = 1;
    private java.lang.Object authorName_;
    /**
     * <code>optional string authorName = 1;</code>
     */
    public boolean hasAuthorName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string authorName = 1;</code>
     */
    public java.lang.String getAuthorName() {
      java.lang.Object ref = authorName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          authorName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string authorName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAuthorNameBytes() {
      java.lang.Object ref = authorName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 2;
    private java.lang.Object address_;
    /**
     * <code>optional string address = 2;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string address = 2;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOOKS_FIELD_NUMBER = 3;
    private java.util.List<com.bhz.netty.protobuf.BookProto.Book> books_;
    /**
     * <code>repeated .Book books = 3;</code>
     */
    public java.util.List<com.bhz.netty.protobuf.BookProto.Book> getBooksList() {
      return books_;
    }
    /**
     * <code>repeated .Book books = 3;</code>
     */
    public java.util.List<? extends com.bhz.netty.protobuf.BookProto.BookOrBuilder> 
        getBooksOrBuilderList() {
      return books_;
    }
    /**
     * <code>repeated .Book books = 3;</code>
     */
    public int getBooksCount() {
      return books_.size();
    }
    /**
     * <code>repeated .Book books = 3;</code>
     */
    public com.bhz.netty.protobuf.BookProto.Book getBooks(int index) {
      return books_.get(index);
    }
    /**
     * <code>repeated .Book books = 3;</code>
     */
    public com.bhz.netty.protobuf.BookProto.BookOrBuilder getBooksOrBuilder(
        int index) {
      return books_.get(index);
    }

    private void initFields() {
      authorName_ = "";
      address_ = "";
      books_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAuthorNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAddressBytes());
      }
      for (int i = 0; i < books_.size(); i++) {
        output.writeMessage(3, books_.get(i));
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAuthorNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAddressBytes());
      }
      for (int i = 0; i < books_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, books_.get(i));
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bhz.netty.protobuf.BookProto.Author parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bhz.netty.protobuf.BookProto.Author parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bhz.netty.protobuf.BookProto.Author parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bhz.netty.protobuf.BookProto.Author parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bhz.netty.protobuf.BookProto.Author parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bhz.netty.protobuf.BookProto.Author parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bhz.netty.protobuf.BookProto.Author parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bhz.netty.protobuf.BookProto.Author parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bhz.netty.protobuf.BookProto.Author parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bhz.netty.protobuf.BookProto.Author parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bhz.netty.protobuf.BookProto.Author prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code Author}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.bhz.netty.protobuf.BookProto.Author, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:Author)
        com.bhz.netty.protobuf.BookProto.AuthorOrBuilder {
      // Construct using com.bhz.netty.protobuf.BookProto.Author.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        authorName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        books_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.bhz.netty.protobuf.BookProto.Author getDefaultInstanceForType() {
        return com.bhz.netty.protobuf.BookProto.Author.getDefaultInstance();
      }

      public com.bhz.netty.protobuf.BookProto.Author build() {
        com.bhz.netty.protobuf.BookProto.Author result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bhz.netty.protobuf.BookProto.Author buildPartial() {
        com.bhz.netty.protobuf.BookProto.Author result = new com.bhz.netty.protobuf.BookProto.Author(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.authorName_ = authorName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.address_ = address_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          books_ = java.util.Collections.unmodifiableList(books_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.books_ = books_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.bhz.netty.protobuf.BookProto.Author other) {
        if (other == com.bhz.netty.protobuf.BookProto.Author.getDefaultInstance()) return this;
        if (other.hasAuthorName()) {
          bitField0_ |= 0x00000001;
          authorName_ = other.authorName_;
          
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000002;
          address_ = other.address_;
          
        }
        if (!other.books_.isEmpty()) {
          if (books_.isEmpty()) {
            books_ = other.books_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureBooksIsMutable();
            books_.addAll(other.books_);
          }
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bhz.netty.protobuf.BookProto.Author parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bhz.netty.protobuf.BookProto.Author) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object authorName_ = "";
      /**
       * <code>optional string authorName = 1;</code>
       */
      public boolean hasAuthorName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string authorName = 1;</code>
       */
      public java.lang.String getAuthorName() {
        java.lang.Object ref = authorName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            authorName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string authorName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAuthorNameBytes() {
        java.lang.Object ref = authorName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string authorName = 1;</code>
       */
      public Builder setAuthorName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        authorName_ = value;
        
        return this;
      }
      /**
       * <code>optional string authorName = 1;</code>
       */
      public Builder clearAuthorName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        authorName_ = getDefaultInstance().getAuthorName();
        
        return this;
      }
      /**
       * <code>optional string authorName = 1;</code>
       */
      public Builder setAuthorNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        authorName_ = value;
        
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 2;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string address = 2;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 2;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        address_ = value;
        
        return this;
      }
      /**
       * <code>optional string address = 2;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = getDefaultInstance().getAddress();
        
        return this;
      }
      /**
       * <code>optional string address = 2;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        address_ = value;
        
        return this;
      }

      private java.util.List<com.bhz.netty.protobuf.BookProto.Book> books_ =
        java.util.Collections.emptyList();
      private void ensureBooksIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          books_ = new java.util.ArrayList<com.bhz.netty.protobuf.BookProto.Book>(books_);
          bitField0_ |= 0x00000004;
         }
      }

      /**
       * <code>repeated .Book books = 3;</code>
       */
      public java.util.List<com.bhz.netty.protobuf.BookProto.Book> getBooksList() {
        return java.util.Collections.unmodifiableList(books_);
      }
      /**
       * <code>repeated .Book books = 3;</code>
       */
      public int getBooksCount() {
        return books_.size();
      }
      /**
       * <code>repeated .Book books = 3;</code>
       */
      public com.bhz.netty.protobuf.BookProto.Book getBooks(int index) {
        return books_.get(index);
      }
      /**
       * <code>repeated .Book books = 3;</code>
       */
      public Builder setBooks(
          int index, com.bhz.netty.protobuf.BookProto.Book value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBooksIsMutable();
        books_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .Book books = 3;</code>
       */
      public Builder setBooks(
          int index, com.bhz.netty.protobuf.BookProto.Book.Builder builderForValue) {
        ensureBooksIsMutable();
        books_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Book books = 3;</code>
       */
      public Builder addBooks(com.bhz.netty.protobuf.BookProto.Book value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBooksIsMutable();
        books_.add(value);

        return this;
      }
      /**
       * <code>repeated .Book books = 3;</code>
       */
      public Builder addBooks(
          int index, com.bhz.netty.protobuf.BookProto.Book value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBooksIsMutable();
        books_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .Book books = 3;</code>
       */
      public Builder addBooks(
          com.bhz.netty.protobuf.BookProto.Book.Builder builderForValue) {
        ensureBooksIsMutable();
        books_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Book books = 3;</code>
       */
      public Builder addBooks(
          int index, com.bhz.netty.protobuf.BookProto.Book.Builder builderForValue) {
        ensureBooksIsMutable();
        books_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Book books = 3;</code>
       */
      public Builder addAllBooks(
          java.lang.Iterable<? extends com.bhz.netty.protobuf.BookProto.Book> values) {
        ensureBooksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, books_);

        return this;
      }
      /**
       * <code>repeated .Book books = 3;</code>
       */
      public Builder clearBooks() {
        books_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);

        return this;
      }
      /**
       * <code>repeated .Book books = 3;</code>
       */
      public Builder removeBooks(int index) {
        ensureBooksIsMutable();
        books_.remove(index);

        return this;
      }

      // @@protoc_insertion_point(builder_scope:Author)
    }

    static {
      defaultInstance = new Author(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Author)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
