// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/protobuf/Employee.proto

package com.bhz.netty.protobuf;

public final class EmployeeProto {
  private EmployeeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface EmployeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Employee)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 3;</code>
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 3;</code>
     */
    int getAge();

    /**
     * <code>optional int32 sex = 4;</code>
     */
    boolean hasSex();
    /**
     * <code>optional int32 sex = 4;</code>
     */
    int getSex();

    /**
     * <code>optional .Employee.Department depart = 5;</code>
     */
    boolean hasDepart();
    /**
     * <code>optional .Employee.Department depart = 5;</code>
     */
    com.bhz.netty.protobuf.EmployeeProto.Employee.Department getDepart();
  }
  /**
   * Protobuf type {@code Employee}
   */
  public static final class Employee extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:Employee)
      EmployeeOrBuilder {
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Employee(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final Employee defaultInstance;
    public static Employee getDefaultInstance() {
      return defaultInstance;
    }

    public Employee getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              age_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              sex_ = input.readInt32();
              break;
            }
            case 42: {
              com.bhz.netty.protobuf.EmployeeProto.Employee.Department.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = depart_.toBuilder();
              }
              depart_ = input.readMessage(com.bhz.netty.protobuf.EmployeeProto.Employee.Department.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(depart_);
                depart_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Employee> PARSER =
        new com.google.protobuf.AbstractParser<Employee>() {
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Employee(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    public interface DepartmentOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Employee.Department)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>required string departId = 1;</code>
       */
      boolean hasDepartId();
      /**
       * <code>required string departId = 1;</code>
       */
      java.lang.String getDepartId();
      /**
       * <code>required string departId = 1;</code>
       */
      com.google.protobuf.ByteString
          getDepartIdBytes();

      /**
       * <code>required string departName = 2;</code>
       */
      boolean hasDepartName();
      /**
       * <code>required string departName = 2;</code>
       */
      java.lang.String getDepartName();
      /**
       * <code>required string departName = 2;</code>
       */
      com.google.protobuf.ByteString
          getDepartNameBytes();
    }
    /**
     * Protobuf type {@code Employee.Department}
     */
    public static final class Department extends
        com.google.protobuf.GeneratedMessageLite implements
        // @@protoc_insertion_point(message_implements:Employee.Department)
        DepartmentOrBuilder {
      // Use Department.newBuilder() to construct.
      private Department(com.google.protobuf.GeneratedMessageLite.Builder builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Department(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

      private static final Department defaultInstance;
      public static Department getDefaultInstance() {
        return defaultInstance;
      }

      public Department getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.ByteString unknownFields;
      private Department(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.ByteString.Output unknownFieldsOutput =
            com.google.protobuf.ByteString.newOutput();
        com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
            com.google.protobuf.CodedOutputStream.newInstance(
                unknownFieldsOutput);
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                departId_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                departName_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          try {
            unknownFieldsCodedOutput.flush();
          } catch (java.io.IOException e) {
          // Should not happen
          } finally {
            unknownFields = unknownFieldsOutput.toByteString();
          }
          makeExtensionsImmutable();
        }
      }
      public static com.google.protobuf.Parser<Department> PARSER =
          new com.google.protobuf.AbstractParser<Department>() {
        public Department parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Department(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Department> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int DEPARTID_FIELD_NUMBER = 1;
      private java.lang.Object departId_;
      /**
       * <code>required string departId = 1;</code>
       */
      public boolean hasDepartId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string departId = 1;</code>
       */
      public java.lang.String getDepartId() {
        java.lang.Object ref = departId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            departId_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string departId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDepartIdBytes() {
        java.lang.Object ref = departId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          departId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DEPARTNAME_FIELD_NUMBER = 2;
      private java.lang.Object departName_;
      /**
       * <code>required string departName = 2;</code>
       */
      public boolean hasDepartName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string departName = 2;</code>
       */
      public java.lang.String getDepartName() {
        java.lang.Object ref = departName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            departName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string departName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDepartNameBytes() {
        java.lang.Object ref = departName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          departName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        departId_ = "";
        departName_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasDepartId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDepartName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getDepartIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getDepartNameBytes());
        }
        output.writeRawBytes(unknownFields);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getDepartIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getDepartNameBytes());
        }
        size += unknownFields.size();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.bhz.netty.protobuf.EmployeeProto.Employee.Department parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.bhz.netty.protobuf.EmployeeProto.Employee.Department parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.bhz.netty.protobuf.EmployeeProto.Employee.Department parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.bhz.netty.protobuf.EmployeeProto.Employee.Department parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.bhz.netty.protobuf.EmployeeProto.Employee.Department parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.bhz.netty.protobuf.EmployeeProto.Employee.Department parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.bhz.netty.protobuf.EmployeeProto.Employee.Department parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.bhz.netty.protobuf.EmployeeProto.Employee.Department parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.bhz.netty.protobuf.EmployeeProto.Employee.Department parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.bhz.netty.protobuf.EmployeeProto.Employee.Department parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.bhz.netty.protobuf.EmployeeProto.Employee.Department prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      /**
       * Protobuf type {@code Employee.Department}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.bhz.netty.protobuf.EmployeeProto.Employee.Department, Builder>
          implements
          // @@protoc_insertion_point(builder_implements:Employee.Department)
          com.bhz.netty.protobuf.EmployeeProto.Employee.DepartmentOrBuilder {
        // Construct using com.bhz.netty.protobuf.EmployeeProto.Employee.Department.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          departId_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          departName_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.bhz.netty.protobuf.EmployeeProto.Employee.Department getDefaultInstanceForType() {
          return com.bhz.netty.protobuf.EmployeeProto.Employee.Department.getDefaultInstance();
        }

        public com.bhz.netty.protobuf.EmployeeProto.Employee.Department build() {
          com.bhz.netty.protobuf.EmployeeProto.Employee.Department result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.bhz.netty.protobuf.EmployeeProto.Employee.Department buildPartial() {
          com.bhz.netty.protobuf.EmployeeProto.Employee.Department result = new com.bhz.netty.protobuf.EmployeeProto.Employee.Department(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.departId_ = departId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.departName_ = departName_;
          result.bitField0_ = to_bitField0_;
          return result;
        }

        public Builder mergeFrom(com.bhz.netty.protobuf.EmployeeProto.Employee.Department other) {
          if (other == com.bhz.netty.protobuf.EmployeeProto.Employee.Department.getDefaultInstance()) return this;
          if (other.hasDepartId()) {
            bitField0_ |= 0x00000001;
            departId_ = other.departId_;
            
          }
          if (other.hasDepartName()) {
            bitField0_ |= 0x00000002;
            departName_ = other.departName_;
            
          }
          setUnknownFields(
              getUnknownFields().concat(other.unknownFields));
          return this;
        }

        public final boolean isInitialized() {
          if (!hasDepartId()) {
            
            return false;
          }
          if (!hasDepartName()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.bhz.netty.protobuf.EmployeeProto.Employee.Department parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.bhz.netty.protobuf.EmployeeProto.Employee.Department) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object departId_ = "";
        /**
         * <code>required string departId = 1;</code>
         */
        public boolean hasDepartId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string departId = 1;</code>
         */
        public java.lang.String getDepartId() {
          java.lang.Object ref = departId_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              departId_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string departId = 1;</code>
         */
        public com.google.protobuf.ByteString
            getDepartIdBytes() {
          java.lang.Object ref = departId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            departId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string departId = 1;</code>
         */
        public Builder setDepartId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          departId_ = value;
          
          return this;
        }
        /**
         * <code>required string departId = 1;</code>
         */
        public Builder clearDepartId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          departId_ = getDefaultInstance().getDepartId();
          
          return this;
        }
        /**
         * <code>required string departId = 1;</code>
         */
        public Builder setDepartIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          departId_ = value;
          
          return this;
        }

        private java.lang.Object departName_ = "";
        /**
         * <code>required string departName = 2;</code>
         */
        public boolean hasDepartName() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string departName = 2;</code>
         */
        public java.lang.String getDepartName() {
          java.lang.Object ref = departName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              departName_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string departName = 2;</code>
         */
        public com.google.protobuf.ByteString
            getDepartNameBytes() {
          java.lang.Object ref = departName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            departName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string departName = 2;</code>
         */
        public Builder setDepartName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          departName_ = value;
          
          return this;
        }
        /**
         * <code>required string departName = 2;</code>
         */
        public Builder clearDepartName() {
          bitField0_ = (bitField0_ & ~0x00000002);
          departName_ = getDefaultInstance().getDepartName();
          
          return this;
        }
        /**
         * <code>required string departName = 2;</code>
         */
        public Builder setDepartNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          departName_ = value;
          
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Employee.Department)
      }

      static {
        defaultInstance = new Department(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Employee.Department)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>optional int32 age = 3;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int SEX_FIELD_NUMBER = 4;
    private int sex_;
    /**
     * <code>optional int32 sex = 4;</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 sex = 4;</code>
     */
    public int getSex() {
      return sex_;
    }

    public static final int DEPART_FIELD_NUMBER = 5;
    private com.bhz.netty.protobuf.EmployeeProto.Employee.Department depart_;
    /**
     * <code>optional .Employee.Department depart = 5;</code>
     */
    public boolean hasDepart() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .Employee.Department depart = 5;</code>
     */
    public com.bhz.netty.protobuf.EmployeeProto.Employee.Department getDepart() {
      return depart_;
    }

    private void initFields() {
      id_ = "";
      name_ = "";
      age_ = 0;
      sex_ = 0;
      depart_ = com.bhz.netty.protobuf.EmployeeProto.Employee.Department.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasDepart()) {
        if (!getDepart().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, age_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, sex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, depart_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, sex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, depart_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bhz.netty.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bhz.netty.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bhz.netty.protobuf.EmployeeProto.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bhz.netty.protobuf.EmployeeProto.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bhz.netty.protobuf.EmployeeProto.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bhz.netty.protobuf.EmployeeProto.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bhz.netty.protobuf.EmployeeProto.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bhz.netty.protobuf.EmployeeProto.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bhz.netty.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bhz.netty.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bhz.netty.protobuf.EmployeeProto.Employee prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.bhz.netty.protobuf.EmployeeProto.Employee, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:Employee)
        com.bhz.netty.protobuf.EmployeeProto.EmployeeOrBuilder {
      // Construct using com.bhz.netty.protobuf.EmployeeProto.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        depart_ = com.bhz.netty.protobuf.EmployeeProto.Employee.Department.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.bhz.netty.protobuf.EmployeeProto.Employee getDefaultInstanceForType() {
        return com.bhz.netty.protobuf.EmployeeProto.Employee.getDefaultInstance();
      }

      public com.bhz.netty.protobuf.EmployeeProto.Employee build() {
        com.bhz.netty.protobuf.EmployeeProto.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bhz.netty.protobuf.EmployeeProto.Employee buildPartial() {
        com.bhz.netty.protobuf.EmployeeProto.Employee result = new com.bhz.netty.protobuf.EmployeeProto.Employee(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.age_ = age_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.depart_ = depart_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.bhz.netty.protobuf.EmployeeProto.Employee other) {
        if (other == com.bhz.netty.protobuf.EmployeeProto.Employee.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasDepart()) {
          mergeDepart(other.getDepart());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (hasDepart()) {
          if (!getDepart().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bhz.netty.protobuf.EmployeeProto.Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bhz.netty.protobuf.EmployeeProto.Employee) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 3;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 age = 3;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 3;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000004;
        age_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 age = 3;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000004);
        age_ = 0;
        
        return this;
      }

      private int sex_ ;
      /**
       * <code>optional int32 sex = 4;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 sex = 4;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>optional int32 sex = 4;</code>
       */
      public Builder setSex(int value) {
        bitField0_ |= 0x00000008;
        sex_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 sex = 4;</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sex_ = 0;
        
        return this;
      }

      private com.bhz.netty.protobuf.EmployeeProto.Employee.Department depart_ = com.bhz.netty.protobuf.EmployeeProto.Employee.Department.getDefaultInstance();
      /**
       * <code>optional .Employee.Department depart = 5;</code>
       */
      public boolean hasDepart() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .Employee.Department depart = 5;</code>
       */
      public com.bhz.netty.protobuf.EmployeeProto.Employee.Department getDepart() {
        return depart_;
      }
      /**
       * <code>optional .Employee.Department depart = 5;</code>
       */
      public Builder setDepart(com.bhz.netty.protobuf.EmployeeProto.Employee.Department value) {
        if (value == null) {
          throw new NullPointerException();
        }
        depart_ = value;

        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .Employee.Department depart = 5;</code>
       */
      public Builder setDepart(
          com.bhz.netty.protobuf.EmployeeProto.Employee.Department.Builder builderForValue) {
        depart_ = builderForValue.build();

        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .Employee.Department depart = 5;</code>
       */
      public Builder mergeDepart(com.bhz.netty.protobuf.EmployeeProto.Employee.Department value) {
        if (((bitField0_ & 0x00000010) == 0x00000010) &&
            depart_ != com.bhz.netty.protobuf.EmployeeProto.Employee.Department.getDefaultInstance()) {
          depart_ =
            com.bhz.netty.protobuf.EmployeeProto.Employee.Department.newBuilder(depart_).mergeFrom(value).buildPartial();
        } else {
          depart_ = value;
        }

        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .Employee.Department depart = 5;</code>
       */
      public Builder clearDepart() {
        depart_ = com.bhz.netty.protobuf.EmployeeProto.Employee.Department.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Employee)
    }

    static {
      defaultInstance = new Employee(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Employee)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
